Installation testen:

In [24]:
import sys
print("python version: ", sys.version)

import numpy as np
print("numpy version: ", np.__version__)




python version:  3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:42:20) 
[Clang 14.0.6 ]
numpy version:  1.24.3


# Beispiele für die "Kreation" von NumPy-Arrays

In [25]:
# ein Numpy array aus eine Liste erzeugen
array1 = np.array([1, 4, 2, 5, 3])

#array1 = np.array([1,3,4])

print(array1,type(array1))

[1 4 2 5 3] <class 'numpy.ndarray'>


In [26]:
# Wenn verschiedene Datentypen im Array sind wird versucht "up-zu-casten" (typisierung (?))  up-casting (engl.)
# d.h. z.B. int zu float, 
x =np.array([3.14, 4, 2, 3])

#x = np.array([3.14, 2., 2, 3, "test"])

print(x,type(x))
print(x.dtype,type(x.dtype))




[3.14 4.   2.   3.  ] <class 'numpy.ndarray'>
float64 <class 'numpy.dtype[float64]'>


In [27]:
# wir können den Datentyp auch explizit übergeben
np.array([1, 2, 3, 4], dtype='float32')

x= np.array([1, 2, 3, 4], dtype='int16')


print(x.dtype,type(x.dtype))

int16 <class 'numpy.dtype[int16]'>


In [28]:
# Erzeugung Mehrdimensionales Numpy-Array (2d) aus eine verschachtelten Liste 

#liste = [[1,2,3],[0,1]] # => Value Error
liste = [[1,2,3],[0,1,3]]

x = np.array(liste) 

print(liste)

print(x,x.dtype,x.ndim) # mit ndim lässt sich die Dimension des Array abfragen







[[1, 2, 3], [0, 1, 3]]
[[1 2 3]
 [0 1 3]] int64 2


In [29]:
# verschachtelte Listen werden zu multidimensionalen Arrays (List Comprehension)

x = np.array([range(i, i + 3) for i in [2, 4, 6]]) #  <= range(2,5),range(4,7),range(6,9)

liste = [range(i, i + 3) for i in [2, 4, 6]]
print(type(liste))
print(liste) # => [range(2, 5), range(4, 7), range(6, 9)]

print(x)






<class 'list'>
[range(2, 5), range(4, 7), range(6, 9)]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [30]:
## Array  Erzeugung weitere Beispiele

np.zeros(10, dtype=int)
np.zeros(10, dtype=np.float64)
np.zeros(10, dtype='float64')
#np.zeros(10, dtype=float64) # kennt Numpy/Pyhton nicht

np.zeros((3,1), dtype=int) # Mehrdimensional



array([[0],
       [0],
       [0]])

In [31]:
# 3x5 float-array mit 1.0 gefüllt
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# 3x5 float-array gefüllt mit 3.14

np.full((3, 5), 3.14)

np.full((4,4),True)



array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
# ein Array mit eine linearen abfolge im Wertebereich [0-20] mit Wert-Abstand 2, - ähnlich zur range Funktion 

np.arange(0, 20, 1)
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
np.arange(0, 10, 0.3) # ?



array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

* mit `reshape(shape)` kann eine Array in eine andere Form gebracht werden
* die shape wird als Tupel angegeben, dabei müssen, die Anzahl der Elemente passen

In [35]:

x = np.arange(9)
x = np.arange(9).reshape((3, 3))


x = np.arange(6).reshape((3, 2)) # => ValueError

x= np.arange(9).reshape((3,3))

x = np.arange(9).reshape((3, 3)).reshape((9,)) # Auch verkettung ist möglich 


#x = np.arange(9).reshape((3, 3)).reshape((9))
#x = np.arange(9).reshape((3, 3)).reshape((9,1))

# vgl x = np.arange(9)
#x = np.arange(9)

print("Number of Dimensions: ",x.ndim)

print(x)


Number of Dimensions:  1
[0 1 2 3 4 5 6 7 8]


## Numpy Array Shapes

![shapes](img/array_shapes.png)

In [36]:
# Array shapes

a = np.arange(4).reshape((4,))
b = np.arange(6).reshape((2,3))
c = np.arange(24).reshape((4,3,2))


print(a,b,c, sep="\n------\n")



[0 1 2 3]
------
[[0 1 2]
 [3 4 5]]
------
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [37]:
# 5 Werte die zwischen 0 und 1 liegen (inclusive)
#  np.linspace(von, bis, anzahl elemente)

np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
# 3x3 array mit "gleichverteilten" Werten zwischen 0 und 1 inclusive  

#np.random.random((3, 3)) 

np.random.random((3, 4)) 




array([[0.78210252, 0.38991787, 0.31246175, 0.79545718],
       [0.36015504, 0.31141228, 0.73349998, 0.75136461],
       [0.30371303, 0.13428118, 0.97023639, 0.62330156]])

#### Normal-Verteilung

"Die Normal- oder Gauß-Verteilung (nach Carl Friedrich Gauß) ist in der Stochastik ein wichtiger Typ stetiger Wahrscheinlichkeitsverteilungen. Ihre Wahrscheinlichkeitsdichtefunktion wird auch _Gauß-Funktion_, _gaußsche Normalverteilung_, _gaußsche Verteilungskurve_, Gauß-Kurve, gaußsche Glockenkurve, gaußsche Glockenfunktion, Gauß-Glocke oder schlicht _Glockenkurve_ genannt."  

"Die besondere Bedeutung der Normalverteilung beruht unter anderem auf dem zentralen Grenzwertsatz, dem zufolge Verteilungen, die durch additive Überlagerung einer großen Zahl von unabhängigen Einflüssen entstehen, unter schwachen Voraussetzungen annähernd normalverteilt sind."

Beispiele:
* ein Dartspieler, der versucht, das „Bull’s-Eye“ zu treffen 
* Finanzmarkt (Preisänderung von Aktien)
* Physik (Messfehler)
* Meteorologie (Regenmenge, Sonnenstunden)
* Biologie (Körpergröße, Länge von Gliedmaßen, Blutdruck)


"Die ___Standardabweichung___ $\sigma$ ist ein Maß für die Streubreite der Werte eines Merkmals rund um dessen Mittelwert (arithmetisches Mittel). Vereinfacht gesagt, ist die Standardabweichung die durchschnittliche Entfernung aller gemessenen Ausprägungen eines Merkmals vom Durchschnitt."  
<https://de.statista.com/statistik/lexikon/definition/126/standardabweichung/>

"Die ___Standardabweichung___ $\sigma$ beschreibt die Breite der Normalverteilung."  
<https://de.wikipedia.org/wiki/Normalverteilung>

<img src="img/standard_abweichung.png" width="800"/>



In [39]:
import numpy as np 
# 3x3 array mit "normalverteilten" Werten:
# um den Mittelwert 0 mit Standard-Abweichung 1 

np.random.normal(0, 1, (3,3))


array([[-0.21006177,  0.01066369,  0.04535769],
       [ 1.32248674,  1.05607653,  0.67744554],
       [-1.53399658, -0.11835047, -1.713399  ]])

In [40]:
# 3x3 Array mit zufallswerten in [0,10) (10 exclusive)
np.random.randint(0, 10, (3, 3)) 

np.random.normal(0, 20, (6, 6))


array([[ -0.68752998,  -4.95525529, -16.01393541, -39.06618427,
         26.31883866, -17.90222266],
       [  9.56741848,  22.8787488 , -32.20703929,  -4.90728858,
        -23.87130015, -19.08184302],
       [-16.36169745, -13.04284541,  24.57591257, -14.33799247,
         -8.12903973,  11.5792419 ],
       [  1.5760412 , -24.94164257,   9.84202094,   8.27883536,
        -49.79274069,  15.13030895],
       [  5.22471247, -18.7693556 ,  15.71297689,  -4.53678687,
         12.02386165, -45.02649085],
       [ 14.7356317 ,  32.46799993,  24.97339594, -24.25765004,
         38.34039034,  25.84081689]])

In [41]:
# 3x3 Einheitsmatrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
import numpy as np
# uninitialisierter array mit Werten die bereits im Speicher stehen !!
np.empty(3)

array([3., 2., 1.])

In [43]:
# Matrix aus 0 mit definierten Diagonal-Elementen
np.diag([1,2,3,5,7])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 7]])

In [44]:
import numpy as np

#np.zeros(3, dtype='float_')

x = np.zeros((3,3), dtype='float_')


print(x.dtype)

float64


## Ein Array aus einer Datei im csv format lesen:

In [45]:
import numpy as np


data = np.genfromtxt('csv/matrix.csv', delimiter=',')

print(data)

FileNotFoundError: csv/matrix.csv not found.

## Ein Array in eine Datei schreiben

In [ ]:
import numpy as np

A = np.arange(20).reshape(4,5)

print(A)
np.savetxt("csv/matrix_out.csv", A, delimiter=",")

## Copies and Views
Ein Numpy-Array kann (in einem "view") direkt über den Datenbuffer geändert werden ohne das Daten kopiert werden müssen oder es kann eine Kopie ("copy") erstellt werden, so daß das Original erhalten bleibt.

* Ein "View" entspricht einem "Teil" des Original Arrays. Änderungen am View oder Original werden auf beiden ausgeführt, da sie den selben Speicherbereich referenzieren
    * Views werden bei Indexierung automatisch erzeugt (keine Kopie !)
    * mit view() lässt sich explizit ein View erzeugen
* Eine "Copy" ist eben eine Kopie des Speicherbereichs an eine anderen Speicher-Position. Änderungen beeinflussen sich daher nicht gegenseitig.
    * eine Kopie kann über .copy() erzeugt werden
    * oder mittels Array-Konstruktor: `np.array(x, copy=True)`


In [ ]:
#Beispiel View:
import numpy as np
x = np.arange(10)
print(x)
y = x[1:3]  # creates a view
print(y)
x[1:3] = [10, 11]
print(x)
print(y) # Änderungen auf dem Original spiegeln sich auch im View wieder

y[0:2] = [22,33]
print(x) # Ändereungen am View spiegeln sich im Original wieder

z = x.view() # erzeugt einen views
z[0:1] = [100] # klammern kann man weglassen
print(x)



[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]
[ 0 22 33  3  4  5  6  7  8  9]
[100  22  33   3   4   5   6   7   8   9]


In [ ]:
#Beispiel Copy:
import numpy as np
x = np.arange(10)
print(x)

z = x.copy() # erzeugt eine Kopie
z[0:1] = [100] #
print(x)

z = np.array(x, copy=True) # erzeugt eine Kopie
z[0:1] = [1001] #
print(z)
print(x)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1001    1    2    3    4    5    6    7    8    9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

a = [[1, 2], [3, 4]]
print(a)

x = np.array(a)
y = x
z = np.array(x, copy=True) 

z = np.copy(x)

x[0,0] = 10 # 2d array !
y[1,1] = 4


print("-----")
print(x,y,z,sep="\n------\n")