#### 1. Schreibe einen Code-Snippet um die Version von numpy auszugeben

In [2]:
import numpy as np
import pandas as pd

print("numpy version: ", np.__version__)
print("pandas version: ", pd.__version__)

numpy version:  1.24.2
pandas version:  1.5.3


#### 2. Teste ob ALLE Elemente ungleich 0 sind und gebe diese Information aus:

In [5]:
import numpy as np 
x1 = np.array([1, 2, 3, 4])

print(np.all(x1 != 0))
# code hier
x2 = np.array([1, 2, 0, 4])
# code hier
print(np.all(x2 != 0))



True
False


#### 3. Teste ob EIN Elemente ungleich 0 ist und gebe diese Information aus:

In [8]:
import numpy as np 
x1 = np.array([1, 2, 3, 4])

# code hier
print(np.any(x1 != 0))

x2 = np.array([1, 2, 0, 4])
x2 = np.array([0, 0, 0, 0])# => false

# code hier
print(np.any(x2 != 0))




True
False



#### 4. Erzeuge eine 3x5 Matrix aus 0'en

In [10]:
##
import numpy as np

# 4.
print(np.zeros((3,5)))
print(np.full((3,5),0.0))



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 5. Erzeuge eine 7x5 Numpy-Matrix aus 5'en

In [11]:
##
#5.
print(np.full((7,5),5.0))

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


#### 6. Erzeuge eine 5x5 Matrix gefüllt mit 0'en und den diagonalen Werten  1, 2, 3, 4, 5.

 $\left[ \begin{array}{rrr}
    1 & 0 & 0 & 0 & 0\\ 
    0 & 2 & 0 & 0 & 0\\ 
    0 & 0 & 3 & 0 & 0\\ 
    0 & 0 & 0 & 4 & 0\\ 
    0 & 0 & 0 & 0 & 5\\ 
    \end{array}\right]$



In [13]:
##

# 6.
np.diag([1,2,3,4,5])

#np.diag(np.array([1,2,3,4,5]))


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 7. Erzeuge ein 2-dimensionales 8x5 Array mit "normalverteilten" Werten mit Standard-abweichung 1 um den Mittelwert 3




In [15]:
import numpy as np

# um den Mittelwert 0 mit Standard-Abweichung 1 
#np.random.normal(0, 1, (3,3))

# 7. 8x5 Array mit Standard-Abweichung 1 um den Mittelwert 3 
np.random.normal(3, 1, (8,5))






array([[3.51535752, 5.53278539, 3.88677158, 2.56723596, 2.34723398],
       [2.76790297, 3.15797643, 2.09276127, 0.83845231, 3.57363604],
       [3.70403507, 2.96565877, 3.82768581, 3.4991672 , 2.71279038],
       [2.91493341, 1.19165925, 1.65490947, 2.04172914, 2.37255952],
       [1.94293087, 2.82644629, 4.26087411, 1.83610569, 2.55671869],
       [3.24944658, 2.17442015, 3.51716192, 1.29454735, 2.7074941 ],
       [1.59381542, 3.44637608, 1.55505185, 2.8083038 , 0.76226615],
       [2.99500664, 4.00897277, 4.53686209, 2.16568625, 2.24790857]])

#### Löse folgendes LGS mit dem Determinanten Verfahren

LGS:  
4x + 3y -1z = 2  
-3x -4y +5y = -5  
-2x +2y +y = 6  


Determinanten Berechnung mit Numpy:  
<https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html>

Determinanten Verfahren:  
<https://www.schullv.de/mathe/basiswissen/lineare_gleichungssysteme/determinantenverfahren>  
<https://de.wikibooks.org/wiki/MathGymOS/_LGS/_Das_Determinanten-Verfahren>  
<https://www.youtube.com/watch?v=a_iwXNHhXa0>  
<https://www.youtube.com/watch?v=uSOdpqLWP4Y>  







In [ ]:
import numpy as np

# Bsp.: berechnung der Determinante von a

a = np.array([[1, 2], [3, 4]])

detA = np.linalg.det(a)






