# Übungsaufgaben Numpy
* ersetzte jeweils die "\<placeholder\>" mit gültigem Python Code

In [1]:
# laden der Numpy-Library für die verwendung in den Beispielen
import numpy as np
print("numpy version: ", np.__version__)

numpy version:  1.24.3


#### 1. Füge die Methode ein  um das Numpy-Array aus einer Liste zu erzeugen

In [2]:

arr = np.<platzhalter>([1, 2, 3, 4, 5])

SyntaxError: invalid syntax (3115812407.py, line 1)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

#### 2. Füge das korrekte Argument ein  um ein Zweidimensionales Numpy-Array zu erzeugen

In [ ]:

arr = np.array([1, 2, 3, 4], <platzhalter>=2)

In [ ]:

arr = np.array([1, 2, 3, 4], ndmin=2)

#### 3. Füge die korrekte Syntax ein um die dimension eines Numpy-Array zu überprüfen

In [ ]:

arr = np.array([1, 2, 3, 4])

print(arr.<platzhalter>)

In [ ]:
print(arr.ndim)

#### 4. Füge die korrekte Syntax ein  um den Datentyp eines Numpy-Array zu überprüfen:

In [ ]:
arr = np.array([1, 2, 3, 4])

print(<platzhalter>)

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


# Array-indexing

#### 5. Füge die korrekte Syntax ein um das erste Element auszugeben

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr<platzhalter>)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])

#### 6. Füge die korrekte Syntax ein um die Zahl 50 auszugeben

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr<platzhalter>)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[4])

#### 7. Füge die korrekte Syntax ein um die Zahl 50 auszugeben

In [ ]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(arr<platzhalter>)

In [ ]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(arr[1,0])

#### 8. Benutze einen negativen Index um das letzte Element auszugeben

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(<platzhalter>)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])

# Array-Slicing

#### 9. Füge die korrekte Syntax ein. Alles beginnend (inclusive) mit dem 2. Element bis zum 5. Element (exclusive) 

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(<placeholder>)

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

#### 10. Füge die korrekte Syntax ein. Alles beginnend (inclusive) mit dem 3. Element bis zum 5. Element (exclusive) 

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(<placeholder>)

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[2:4])

[20 25]


#### 11. Füge die korrekte Syntax ein. Jedes 2. Element

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(<placeholder>)

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[::2])

[10 20 30 40]


### Slicing in 2-d arrays

#### 11.2 Füge die korrekte Syntax ein um [[3,4],[9,10]] auszugeben (*)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(<placeholder>)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[0:2,2:4])

[[ 3  4]
 [ 9 10]]


#### 11.3 Füge die korrekte Syntax ein um [[1,2,3,4,5,6]] auszugeben (*)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(<placeholder>)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[0:1,:])

[[1 2 3 4 5 6]]


# Daten-Typen

#### 12. Füge die korrekte Syntax ein um zu die Array-Elemente als float64 zu definieren

In [ ]:
arr = np.array([1, 2, 3, 4], <platzhalter>)
print(arr)

[1. 2. 3. 4.]


In [ ]:
arr = np.array([1, 2, 3, 4], dtype=np.float64)
print(arr)

# Copy vs View

#### 13. Füge die korrekte Syntax ein um eine Kopie des Arrays zu erzeugen

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = <platzhalter>

print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

print(x)

#### 14. Füge die korrekte Syntax ein um einen View des Arrays zu erzeugen


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = <platzhalter>

print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()

print(x)

[1 2 3 4 5]


# Array Shape

#### 15. Füge die korrekte Syntax ein um die shape des Arrays zu prüfen

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)


(5,)


#### 16. Füge die korrekte Syntax ein um aus dem 1-d-Array einen 2-d-Array zu machen (es gibt mehrere mögliche Shapes) 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = <platzhalter>

print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape((4, 3))

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 17. Füge die korrekte Syntax ein um aus dem 2-d Array einen 1-D Array zu machen

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

newarr = <platzhalter>

print(newarr)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape((12,))
#newarr = arr.reshape(-1)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
